# Generated by Django 3.2.9 on 2022-01-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='media/college_logo')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('1', 'CollegeAdmin'), ('2', 'Faculty'), ('3', 'Student')], default=1, max_length=50),
        ),
    ]
