# Generated by Django 3.2.9 on 2022-01-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_cource_semester_subject_subjecttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='cource',
            new_name='course',
        ),
    ]
