# Generated by Django 3.2.9 on 2022-01-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_rename_cource_semester_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cource',
            new_name='Course',
        ),
    ]
