# Generated by Django 3.2.9 on 2022-01-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_rename_cource_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.CharField(max_length=100)),
                ('session_end', models.CharField(max_length=100)),
            ],
        ),
    ]
