# Generated by Django 3.2.9 on 2022-01-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_auto_20220112_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='college.sessionyear'),
        ),
    ]
