# Generated by Django 4.0.1 on 2022-01-12 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='college.sessionyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
