# Generated by Django 3.2.9 on 2022-01-31 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_auto_20220131_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='session_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.sessionyear'),
            preserve_default=False,
        ),
    ]
