# Generated by Django 3.2.9 on 2022-03-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_auto_20220131_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=17),
            preserve_default=False,
        ),
    ]
