# Generated by Django 3.2.9 on 2022-03-13 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2002, 5, 7, 0, 0)),
            preserve_default=False,
        ),
    ]
