# Generated by Django 3.2.9 on 2022-03-19 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_auto_20220313_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to='media/profile_pic', validators=[django.core.validators.FileExtensionValidator(['jpg'])]),
        ),
    ]
