# Generated by Django 3.2.9 on 2022-03-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Suggestion',
        ),
    ]
