# Generated by Django 3.2.9 on 2022-03-22 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_rename_feedback_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
