# Generated by Django 3.2.9 on 2022-04-04 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0022_suggestion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
