# Generated by Django 3.2.9 on 2022-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_paper_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
