# Generated by Django 3.2.9 on 2022-04-05 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0024_auto_20220404_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(default='media/college_logo/AdminLTELogo.png', upload_to='media/college_logo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.college'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='media/profile_pic/default-150x150.png', upload_to='media/profile_pic'),
        ),
    ]
